name: Continous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  black:
    name: Verify black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
      - name: Python dependencies
        run: pip install -r requirements/development.txt
      - name: Verify black
        run: black --line-length=100 --skip-string-normalization --check .
  ruff:
    name: Verify ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
      - name: Python dependencies
        run: pip install -r requirements/development.txt
      - name: Verify ruff
        run: ruff .
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - name: Python ${{ matrix.python-version }} dependencies
        run: pip install -r requirements/development.txt
      - name: Python ${{ matrix.python-version }} tests
        run: py.test --cov=dev
