name: Continous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  black:
    name: Verify black
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Python dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements/development.txt
      - name: Verify black
        run: venv/bin/black --line-length=100 --skip-string-normalization --check .
  ruff:
    name: Verify ruff
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Python dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements/development.txt
      - name: Verify ruff
        run: venv/bin/ruff .
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: python:3.11
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - name: Python ${{ matrix.python-version }} dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements/development.txt
      - name: Python ${{ matrix.python-version }} tests
        run: venv/bin/py.test --cov=dev
